### ISSUE TITLE
Updating TFQA

### ISSUE THREAD

**Issue by mpeeples2008** [sslarch/tfqar#2]
I just found this today. Thanks for linking to some of the TFQA things I've updated. I've actually got a lot more of this implemented in R in various formats and would be happy to collaborate on filling this in a bit more if you're interested. You could email me at Matthew.Peeples@asu.edu if you want to chat about it.

**Comment by joeroe** [comment]
Thanks @mpeeples2008. I've sent you an email from `joe at joeroe dot io` (sometimes it gets stuck in people's spam filter).
